name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Linter
        run: pnpm lint

      - name: Run Unit & Integration Tests
        run: pnpm test

      - name: Build Turbo Monorepo
        run: pnpm build

      - name: Docker Build Check
        run: docker build -t payment-api:test -f apps/payment-api/Dockerfile .